PB_Django_Template/urls.py
from django.contrib import admin
from django.urls import path, include
from my_app import views

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', views.CholladaHomePage.as_view(template_name='my_app/Chollada_Apartment.html'), name='Chollada_Apartment'),

    # path('users/', include('users.urls',namespace='users')),
    path('users/', include('users.urls')),
    # path('users/', include('django.contrib.auth.urls')),

    # path('my_app/', include('my_app.urls', namespace='my_app')),
    path('my_app/', include('my_app.urls')),
    path('my_app/', include('django.contrib.auth.urls')),

]

admin.site.site_header = 'Chollada Apartment Administration'

my_app/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('admin_page/', views.admin_page, name='admin_page'),
    path('', views.gateway, name='gateway'),  # one only ... blank ('')

    path('create_contract/', views.create_contract, name='create_contract'),

    path('billing/', views.billing, name='billing'),

    path('payment_individual/', views.payment_individual, name='payment_individual'),
    path('pay_rent/str<bref>/', views.pay_rent, name='pay_rent'),

    path('report_type/', views.report_type, name='report_type'),
    path('report_parameters/', views.report_parameters, name='report_parameters'),
    path('current_tenant/', views.current_tenant, name='current_tenant'),
    path('extra_service/', views.extra_service, name='extra_service'),
    path('elec_cpu_change/', views.elec_cpu_change, name='elec_cpu_change'),
    path('water_cpu_change/', views.water_cpu_change, name='water_cpu_change'),
    path('room_type_rate/', views.room_type_rate, name='room_type_rate'),
    path('current_tenant/', views.current_tenant, name='current_tenant'),
    path('vacant_rooms/', views.vacant_rooms, name='vacant_rooms'),
    path('monthly_report_mini/', views.monthly_report_mini, name='monthly_report_mini'),

    path('misc_contents/', views.misc_contents, name='misc_contents'),
    path('manage_users/', views.manage_users, name='manage_users'),
    path('user_list_to_delete/', views.user_list_to_delete, name='user_list_to_delete'),
    path('delete_user/<str:rmn>/', views.delete_user, name='delete_user'),
    path('confirm_delete_user/<str:k>/', views.confirm_delete_user, name='confirm_delete_user'),
    path('register/', views.Register.as_view(), name='register'),
    path('register/done/', views.register_done, name='register_done'),
    path('change_password/', views.change_password, name='change_password'),

    path('maintenance_charge/', views.maintenance_charge, name='maintenance_charge'),

    path('new_tenant/', views.new_tenant, name='new_tenant'),
    path('tenant_profile/', views.tenant_profile, name='tenant_profile'),
    path('tenant_bill/', views.tenant_bill, name='tenant_bill'),
    path('tenant_feedback/', views.tenant_feedback, name='tenant_feedback'),

    # path('payment/', views.payment, name='payment'),
    # path('register new users/', views.Register_new_users, name='register_new_users'),
    # path('confirm_delete/', views.confirm_delete, name='confirm_delete'),
    # path('reset_password/', views.reset_password, name='reset_password'),
    # path('tenant_page/', views.tenant_page, name='tenant_page'),
    # path('monthly_report/', views.monthly_report, name='monthly_report'),
    # path('tenant_comment/', views.tenant_comment, name='tenant_comment'),
    # path('send_sms_to_individual_room/', views.send_sms_to_individual_room, name='send_sms_to_individual_room'),
    # path('send_general_sms/', views.send_general_sms, name='send_general_sms'),
    # path('send_bill_sms_to_all_tenants/', views.send_bill_sms_to_all_tenants, name='send_bill_sms_to_all_tenants'),
    # path('tenant_bill/', views.tenant_bill, name='tenant_bill'),

    # path('confirmation/', views.send_sms_confirmation, name='confirmation'),
    # path('send_sms_execution/', views.send_sms_execution, name='send_sms_execution'),

]

users/urls.py
from django.urls import path

from . import views

app_name='users'

urlpatterns = [
    # path('register/', views.Register.as_view(), name='register'),
    # path('register/done/', views.register_done, name='register_done')
]

my_app/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth import get_user_model

CUser = get_user_model()  # Custom User


class Room_type(models.Model):
    desc = models.CharField(max_length=250)
    rate = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.desc


class Room(models.Model):
    room_type = models.ForeignKey(Room_type, on_delete=models.CASCADE)
    room_no = models.CharField(max_length=4)

    def __str__(self):
        return self.room_no


class Extra(models.Model):
    desc = models.CharField(max_length=100)
    cpu = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return self.desc


class Billing(models.Model):
    STATUS_CHOICE = (('open', 'OPEN'), ('close', 'CLOSE'),)

    bill_ref = models.CharField(max_length=6)
    # bill_date = models.DateTimeField(auto_now_add=True)
    # bill_date = models.DateTimeField(auto_now_add=True)
    bill_date = models.DateField(auto_now_add=True)

    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')
    tenant_name = models.CharField(max_length=100)
    room_no = models.CharField(max_length=4)
    room_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    room_acc_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    electricity_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    water_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    common_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    other_ser_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    overdue_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    bill_total = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    payment_date = models.DateField(blank=True, null=True)
    payment_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cf_amount = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    class Meta:
        ordering = ('-bill_date',)

    def __str__(self):
        return 'Bill for room number: {} Status: {}'.format(self.room_no, self.status)

    def get_absolute_url(self):
        return reverse('pay_rent', args=[str(self.bill_ref)])


class TenantProfile(models.Model):
    # tenant = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    tenant = models.OneToOneField(CUser, on_delete=models.CASCADE)
    pin = models.CharField(max_length=13, unique=True)
    phone = models.CharField(max_length=10)
    room_no = models.OneToOneField(Room, on_delete=models.CASCADE, unique=True)
    term = models.PositiveSmallIntegerField(default=12)
    start_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    deposit = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    deduct = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    cum_ovd = models.DecimalField(max_digits=7, decimal_places=2, blank=True, default=0)
    adjust = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    photo = models.ImageField(upload_to='users/%Y/%m/%d/', blank=True)
    extra = models.ManyToManyField(Extra)
    bill_date = models.DateField(auto_now=True, blank=True)
    # USE PLACEHOLDER (NO DEFAULT VALUE) INITIAL VALUE TO BE PROVIDED WHEN SAVE TO DB
    elec_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    water_unit = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    late_fee = models.DecimalField(max_digits=7, decimal_places=2, default=0)  # no need to use placeholder
    maint_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)

    def __str__(self):
        return 'Profile for user {}'.format(self.tenant.first_name)

    def get_absolute_url(self):
        return reverse('fill_bill', args=[self.room_no])

    #
    # def get_absolute_url(self):
    #     return reverse('fill_bill', args=[self.room_no])

    # def get_absolute_url(self):
    #     return reverse('blog:post_detail',
    #                    args=[self.publish.year,
    #                          self.publish.month,
    #                          self.publish.day,
    #                          self.slug])


class MaintenanceCharge(models.Model):
    STATUS_CHOICE = (('open', 'OPEN'), ('close', 'CLOSE'),)

    room_no = models.ForeignKey(Room, on_delete=models.CASCADE)
    desc = models.CharField(max_length=100)
    # job_cost = models.DecimalField(max_digits=7, decimal_places=2, default=0)
    job_cost = models.DecimalField(max_digits=7, decimal_places=2)  # use placeholder (no default)
    status = models.CharField(max_length=5, choices=STATUS_CHOICE, default='open')
    job_date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-job_date',)

templates/my_app/admin_page.html
{% extends "app_base_html.html" %}
{% load static %}

{% block title %}Admin page{% endblock %}


{% block script %}
{% endblock %}



{% block content %}

    {{ section }}

{% endblock %}

templates/my_app/billing.html
{% extends "app_base_html.html" %}
{% load static %}
{% load account_tags %}

{% block title %}Billing{% endblock %}

{% block script %}
    <link href="{% static "css/app_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}

    <style>

        #hx {
            float: left;
        }

        #dx {
            clear: both;
        }

        #hnam {

            display: block;
            width: 13em;
            color: white;
            background-color: blue;
            float: left;
            text-align: center;
            line-height: 1.5em;

        }

        #hphone {
            display: block;
            width: 7em;
            color: white;
            background-color: blue;
            float: left;
            text-align: center;
            line-height: 1.5em;
        }

        #hroom {
            display: block;
            width: 4.25em;
            color: white;
            background-color: red;
            float: left;
            text-align: center;
            line-height: 1.5em;

        }

        .name {
            display: block;
            width: 13em;
            float: left;

            line-height: 1.5em;

        }

        .phone {
            display: block;
            width: 7em;
            text-align: center;
            float: left;
            line-height: 1.5em;
        }

        .room {
            display: block;
            width: 4.25em;
            color: #de1710;
            text-align: center;
            float: left;
            line-height: 1.5em;
        }

        .eu, .wu, .mc {
            width: 7em;
            text-align: center;
            color: red;
            background-color: lightskyblue;
            margin-left: .25em;

            line-height: 1.5em;
        }

        .submit button {
            width: 8em;
            font-size: large;
            background-color: red;
            border-color: red;
            border-radius: 15px;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }

        .submit button:hover {
            color: black;
        }

    </style>

{% endblock %}


{% block content %}
    <h1>Create Bills</h1>

    <div id="hx">
        <label id="hnam">NAME</label>
        <label id="hphone">PHONE</label>
        <label id="hroom">ROOM</label>
        <br>
    </div>


    <div id="dx">

        <form action="." method="post">
            {% csrf_token %}


            {% for data in tenant_pf %}

                {% if data.room_no.room_no == '101A' %}
                    {% display_tenant_data '101A' %}
                    {{ rm101a_form.elec_unit }}
                    {{ rm101a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '102A' %}
                    {% display_tenant_data '102A' %}
                    {{ rm102a_form.elec_unit }}
                    {{ rm102a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '103A' %}
                    {% display_tenant_data '103A' %}
                    {{ rm103a_form.elec_unit }}
                    {{ rm103a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '104A' %}
                    {% display_tenant_data '104A' %}
                    {{ rm104a_form.elec_unit }}
                    {{ rm104a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '105A' %}
                    {% display_tenant_data '105A' %}
                    {{ rm105a_form.elec_unit }}
                    {{ rm105a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '106A' %}
                    {% display_tenant_data '106A' %}
                    {{ rm106a_form.elec_unit }}
                    {{ rm106a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '201A' %}
                    {% display_tenant_data '201A' %}
                    {{ rm201a_form.elec_unit }}
                    {{ rm201a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '202A' %}
                    {% display_tenant_data '202A' %}
                    {{ rm202a_form.elec_unit }}
                    {{ rm202a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '203A' %}
                    {% display_tenant_data '203A' %}
                    {{ rm203a_form.elec_unit }}
                    {{ rm203a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '204A' %}
                    {% display_tenant_data '204A' %}
                    {{ rm204a_form.elec_unit }}
                    {{ rm204a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '205A' %}
                    {% display_tenant_data '205A' %}
                    {{ rm205a_form.elec_unit }}
                    {{ rm205a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '206A' %}
                    {% display_tenant_data '206A' %}
                    {{ rm206a_form.elec_unit }}
                    {{ rm206a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '301A' %}
                    {% display_tenant_data '301A' %}
                    {{ rm301a_form.elec_unit }}
                    {{ rm301a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '302A' %}
                    {% display_tenant_data '302A' %}
                    {{ rm302a_form.elec_unit }}
                    {{ rm302a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '303A' %}
                    {% display_tenant_data '303A' %}
                    {{ rm303a_form.elec_unit }}
                    {{ rm303a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '304A' %}
                    {% display_tenant_data '304A' %}
                    {{ rm304a_form.elec_unit }}
                    {{ rm304a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '305A' %}
                    {% display_tenant_data '305A' %}
                    {{ rm305a_form.elec_unit }}
                    {{ rm305a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '306A' %}
                    {% display_tenant_data '306A' %}
                    {{ rm306a_form.elec_unit }}
                    {{ rm306a_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '201B' %}
                    {% display_tenant_data '201B' %}
                    {{ rm201b_form.elec_unit }}
                    {{ rm201b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '202B' %}
                    {% display_tenant_data '202B' %}
                    {{ rm202b_form.elec_unit }}
                    {{ rm202b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '203B' %}
                    {% display_tenant_data '203B' %}
                    {{ rm203b_form.elec_unit }}
                    {{ rm203b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '204B' %}
                    {% display_tenant_data '204B' %}
                    {{ rm204b_form.elec_unit }}
                    {{ rm204b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '205B' %}
                    {% display_tenant_data '205B' %}
                    {{ rm205b_form.elec_unit }}
                    {{ rm205b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '301B' %}
                    {% display_tenant_data '301B' %}
                    {{ rm301b_form.elec_unit }}
                    {{ rm301b_form.water_unit }}
                    <br>
                {% endif %}


                {% if data.room_no.room_no == '302B' %}
                    {% display_tenant_data '302B' %}
                    {{ rm302b_form.elec_unit }}
                    {{ rm302b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '303B' %}
                    {% display_tenant_data '303B' %}
                    {{ rm303b_form.elec_unit }}
                    {{ rm303b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '304B' %}
                    {% display_tenant_data '304B' %}
                    {{ rm304b_form.elec_unit }}
                    {{ rm304b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '305B' %}
                    {% display_tenant_data '305B' %}
                    {{ rm305b_form.elec_unit }}
                    {{ rm305b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '401B' %}
                    {% display_tenant_data '401B' %}
                    {{ rm401b_form.elec_unit }}
                    {{ rm401b_form.water_unit }}
                    <br>
                {% endif %}


                {% if data.room_no.room_no == '402B' %}
                    {% display_tenant_data '402B' %}
                    {{ rm402b_form.elec_unit }}
                    {{ rm402b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '403B' %}
                    {% display_tenant_data '403B' %}
                    {{ rm403b_form.elec_unit }}
                    {{ rm403b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '404B' %}
                    {% display_tenant_data '404B' %}
                    {{ rm404b_form.elec_unit }}
                    {{ rm404b_form.water_unit }}
                    <br>
                {% endif %}

                {% if data.room_no.room_no == '405B' %}
                    {% display_tenant_data '405B' %}
                    {{ rm405b_form.elec_unit }}
                    {{ rm405b_form.water_unit }}
                    <br>
                {% endif %}


            {% endfor %}
            <div class="submit">
                <button type="submit">Create Billing</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/my_app/change_password.html
{% extends "app_base_html.html" %}

{% load static %}

{% block title %}Change password{% endblock %}


{% block style %}
    <style>
        body {
            margin: 0;
            padding: 0;
            font-family: helvetica, sans-serif;
        }

        #content {
            padding: 20px 100px;
        }

        div.contract label, div.extra label {
            color: black;
            float: left;
            width: 6em;
            font-weight: bold;
            text-align: right;
            margin-right: .15em;
        {#background-color: #aaaaaa;#}

        }

        #id_pin, #id_phone, #id_room_no, #id_term,
        #id_start_date, #id_end_date, #id_deposit, #id_deduct, #id_cum_ovd, #id_adjust, #id_photo,
        #id_username, #id_first_name, #id_last_name, #id_password, #id_password2 {
            width: 10em;
            background-color: lightblue;
            margin-top: 0;

        }

        div.contract fieldset {
            width: 22em;
            height: 23em;
            float: left;

        {#    margin-top: 1em;#}{#    margin-bottom: 1em;#}{#    padding-top: .5em;#}

        }

        div.contract legend {

            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;

        }

        div.extra fieldset {
            width: 18em;
            height: 23em;

        {#margin-top: 1em;#}{#margin-bottom: 1em;#}{#padding-top: .5em;#}
        }

        div.extra legend {

            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;

        }

        #id_photo {
            font-weight: bold;
            color: red;
            width: 16em;
        }

        div.submit {

        {#margin-left: 17em;#}{#clear: both;#}{#padding: 1em;#}

        }

        div.submit button {
            width: 9em;
            font-size: large;
            background-color: red;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }


    </style>
{% endblock %}


{% block content %}
    <h1>Change_password</h1>
{% endblock %}

templates/my_app/display_tenant_data.html
<span class="name">{{ tenant_data.tenant.first_name }} {{ tenant_data.tenant.last_name }}</span>
<span class="phone">{{ tenant_data.phone }}</span>
<span class="room">{{ tenant_data.room_no }}</span>

templates/my_app/maintenanace_charge.html
{% extends "app_base_html.html" %}

{% load static %}
{#{% load widget_tweaks %}#}

{% block title %}New maintenance charge{% endblock %}

{% block script %}

    <link href="{% static "css/app_body.css" %}" rel="stylesheet">

{% endblock %}


{% block style %}
    <style>

        #content {
            font: 90% Arial, Helvetica, sans-serif;
            width: 95%;
            padding: 2em;
            margin: 2px;
        }

        #lb1, #lb2 {
            display: block;
            color: black;
            width: 6em;

            line-height: 1.8em;

            font-weight: normal;
            text-align: right;
            margin-right: .25em;
            background-color: #aaaaaa;
            float: left;

        }

        .ma_cost #id_room_no,
        .ma_cost #id_job_cost {
            width: 6em;

            font-size: 100%;

            text-align: center;

            background-color: lightskyblue;
            margin-top: 0;

            float: left;
        }

        .ma_cost fieldset {
            width: 18em;
            height: 8em;
        }

        .ma_cost legend {
            color: blue;
            font-weight: bold;
            font-size: 125%;
            margin-bottom: .5em;
        }


        .submit button {
            width: 5em;
            font-size: large;
            background-color: red;
            border-color: red;
            border-radius: 15px;
            color: white;
            margin-top: .5em;
            padding: .3em;
        }

        .submit button:hover {
            color: black;
        }


    </style>

{% endblock %}


{% block content %}
    <form action="." method="post">

        {% csrf_token %}
        <div class="ma_cost">
            <fieldset>
                <legend align="top">MAINTENANCE CHARGE</legend>
                <label for="id_room_no" id="lb1">ROOM NO:</label>{{ maintenance_form.room_no }} <br><br>
                <label for="id_job_cost" id="lb2">COST:</label>{{ maintenance_form.job_cost }}
            </fieldset>
        </div>

        <div class="submit">
            <button type="submit">Submit</button>
        </div>


    </form>



{% endblock %}

templates/my_app/misc_contents.html
{% extends "app_base_html.html" %}
{% load static %}

{% block title %}Misc Contents{% endblock %}

{% block script %}
    <link href="{% static "css/app_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}

    <style>

        div #topic ul {
            list-style-type: disc;
            color: red;
            font-size: larger;
            font-weight: bold;
        }

        #topic a {
            color: blue;
            text-decoration: none;
        }

        #topic a:hover {
            color: red;
            font-weight: bold;
            text-decoration: none;
        }

    </style>

{% endblock %}

{% block content %}
    <h1>Contents:</h1>

    <div id="topic">

        <ul>
            <li><p><a href="{% url 'manage_users' %}">Manage Users</a></p></li>
            {#            <li><p><a href="{% url 'confirmation' %}">Send Billing SMS to all tenants</a></p></li>#}
            {#            <li><p><a href="{% url 'send_sms_to_individual_room' %}">Send Billing SMS to individual tenant</a></p></li>#}
            {#                        <li><p><a href="{% url 'send_general_sms' %}">Send general SMS</a></p></li>#}
            <li><p><a href="{% url 'maintenance_charge' %}">Monthly Maintenance Charge</a></p></li>
        </ul>

    </div>


{% endblock %}

templates/my_app/new_tenant.html
{% extends "app_base_html.html" %}
{% load static %}
{% load humanize %}

{% block title %}Tenant Bil{% endblock %}

{% block script %}
    <link href="{% static "css/app_body.css" %}" rel="stylesheet">
{% endblock %}

{% block style %}
{##}
{#    <style>#}
{##}
{#        label {#}
{#            display: block;#}
{#            width: 18em;#}
{#            font-size: medium;#}
{#            font-weight: bold;#}
{#            color: blue;#}
{#            float: left;#}
{#            text-align: right;#}
{#            padding-right: .5em;#}
{#        }#}
{##}
{#        .hlab {#}
{#            display: block;#}
{#            width: 4.75em;#}
{#            font-size: medium;#}
{#            font-weight: bold;#}
{#            color: black;#}
{#            text-align: right;#}
{#            padding-right: .5em;#}
            {#background: lightsteelblue;#}
{##}
{#        }#}
{##}
{##}
{#    </style>#}
{##}
{#    <style>#}
{##}
{#        table {#}
{#            border-collapse: collapse;#}
{#            border: 1px solid black;#}
{#            white-space: nowrap;#}
{#        }#}
{##}
{#        thead, tfoot {#}
{#            background-color: lightblue;#}
{#        }#}
{##}
{#        tfoot {#}
{#            font-weight: bold;#}
{#        }#}
{##}
{#        th, td {#}
{#            border: 1px solid black;#}
{#            padding: .2em .7em;#}
{#            text-align: right;#}
{#        }#}
{##}
{#        th:first-child, td:first-child {#}
{#            text-align: left;#}
{#        }#}
{##}
{#        th:first-child {#}
{##}
{#            vertical-align: center;#}
{#        }#}
{##}
{#        th:nth-child(2) {#}
{#            text-align: center;#}
{#        }#}
{##}
{#        tr:nth-child(1) th {#}
{#            vertical-align: center;#}
{#            text-align: center;#}
{#            color: black;#}
{#        }#}
{##}
{#        tfoot tr:nth-child(1) th {#}
{#            text-align: center;#}
{#            vertical-align: center;#}
{#            color: black;#}
{#        }#}
{#    #status{#}
{#        color: red;#}
{#        font-weight: bold;#}
{#    }#}
{##}
{##}
{#    </style>#}
{##}
{##}

{% endblock %}


{% block content %}

<p style ="font-size:150%;color: blue">Welcome <strong>K. {{tenant_name }}</strong> to Chollada Apartment !!!</p>


{% endblock %}

templates/my_app/payment_individual_tag.html
{% load humanize %}

<span class="nam">{{ tenant_bill.tenant_name }} </span>
<a href="{{ tenant_bill.get_absolute_url }}"><span class="rn">{{ tenant_bill.room_no }}</span></a>
<span class="rcac">{{ room_cost_acc|floatformat:0|intcomma }}</span>
<span class="ec">{{ tenant_bill.electricity_cost|floatformat:0|intcomma }}</span>
<span class="wc">{{ tenant_bill.water_cost|floatformat:0|intcomma }}</span>
<span class="csc">{{ tenant_bill.common_ser_cost|floatformat:0|intcomma }}</span>
<span class="osc">{{ tenant_bill.other_ser_cost|floatformat:0|intcomma }}</span>
<span class="ovd">{{ tenant_bill.overdue_amount|floatformat:0|intcomma }}</span>

<span class="misc">{{ bill_misc|floatformat:0|intcomma }}</span>

<span class="bt">{{ tenant_bill.bill_total|floatformat:0|intcomma }}</span>